name: Upload Docker image Package

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DDNS_GHCR_TOKEN }}
    
    - name: 'Build and push image'
      run: |
        docker build . --tag ghcr.io/aaronmbdev/cloudflare-ddns-service:latest
        docker push ghcr.io/aaronmbdev/cloudflare-ddns-service:latest
