name: Upload Docker image Package

on:
  workflow_dispatch:

jobs:
  bump_version:
    runs-on: ubuntu-latest
    outputs:
      NEW_VERSION: ${{ steps.bump_version.outputs.NEW_VERSION }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install semantic versioning
        run: pip install semantic-version
      - name: Bump version and commit changes
        id: bump_version
        run: |
          current_version=$(python -c "import app.__version__ as v; print(v.__version__)")
          new_version=$(python -c "from semantic_version import Version; print(Version('$current_version').next_patch())")
          sed -i -E "s/__version__ = \"[^\"]+\"/__version__ = \"$new_version\"/" app/__version__.py
          git add app/__version__.py
          git config user.name "[Github automation]"
          git config user.email "aaron@mbotton.com"
          git commit -m "Bump version to $new_version"
          echo "NEW_VERSION=$new_version" >> $GITHUB_OUTPUT
          git push
  build-and-push:
    needs: bump_version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DDNS_GHCR_TOKEN }}
    
    - name: 'Build and push image'
      run: |
        docker build . --tag ghcr.io/aaronmbdev/cloudflare-ddns-service:${{needs.bump_version.outputs.NEW_VERSION}}
        docker push ghcr.io/aaronmbdev/cloudflare-ddns-service:${{needs.bump_version.outputs.NEW_VERSION}}
